sudo: required
services:
  - docker

before_install:
  # the last ./client is instead of the "." we usually do on build
  - docker build -t chenmargalit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chenmargalit/react-test npm test

after_success:
  - docker build -t chenmargalit/multi-client ./client
  - docker build -t chenmargalit/multi-nginx ./nginx
  - docker build -t chenmargalit/multi-server ./server
  - docker build -t chenmargalit/multi-worker ./worker

# login to docker cli
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push images to docker hub
- docker push chenmargalit/multi-client
- docker push chenmargalit/multi-nginx
- docker push chenmargalit/multi-server
- docker push chenmargalit/multi-worker
